services:
  web:
    container_name: store-locator
    image: wordpress:latest
    volumes:
      - store_locator:/var/www/html
      - ./:/var/www/html/wp-content/plugins/store-locator
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - store-locator-network
  
  db:
    container_name: store-locator-db
    image: mysql:8.0
    volumes:
      - store_locator_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    networks:
      - store-locator-network

volumes:
  store_locator:
  store_locator_db:


networks:
  store-locator-network:
    driver: bridge
    external: true

